# 서버 설정
server:
  port: 3000

# 데이터 베이스 연결 설정
datasource:
  driverClassName: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521:orcl
  username: BOARDPROJECT
  password: _aA123456

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: oracle.jdbc.OracleDriver
    hibernate:
      ddlAuto: update
      naming:
        physical-strategy: org:hibernate:boot:model:naming:PhysicalNamingStrategyStandardImpl
      open-in-view: false

      logging:
        level:
          org:
            hibernate:
              type:
                descriptor:
                  sql: trace


#파일 업로드 설정
  spring:
    servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 60MB

# 파일 업로드 경로 설정
  file:
    upload:
      path: C:/uploads/
      url: /uploads/