# 서버 설정
server:
  port: 3001


spring:
  #파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 60MB
  # 라이브 리로드 설정
  devtools:
    livereload:
      enabled: true

  thymeleaf: # Thymeleaf (1. 루트폴더 변경, 2. 타임리프 캐시 설정 변경)
    prefix: file:src/main/resources/templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false

  datasource: # 데이터 베이스 연결 설정
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: BOARDPROJECT
    password: _aA123456

# JPA 설정
  jpa:
    open-in-view: false
    #database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-Auto: update

  logging:
    level:
      org:
        hibernate:
          SQL: debug
          type:
            descriptor:
              sql: trace
        springframework:
          core:
            LocalVariableTableParameterNameDiscoverer: error

  file: # 파일 업로드 경로 설정
    upload:
      path: C:/uploads/
      url: /uploads/

  web: # 정적 자원 설정(CSS, JS, 이미지)
    resources:
      static-locations: file:src/main/resources/static/

